SELECT NAME.NAME_ID, NAME.FIRST,  NAME.MIDDLE, NAME.LAST FROM NAME INNER JOIN CONTACT ON NAME.NAME_ID = CONTACT.NAME_ID;

SELECT CONTACT.CONTACT_ID, ADDRESS.ADDRESS_ID, ADDRESS.STREET,  ADDRESS.CITY, ADDRESS.STATE, ADDRESS.ZIP,  FROM ADDRESS INNER JOIN CONTACT ON ADDRESS.ADDRESS_ID = CONTACT.ADDRESS_ID;

SELECT CONTACT.CONTACT_ID, NAME.FIRST, NAME.LAST, ADDRESS.ADDRESS_ID, ADDRESS.STREET,  ADDRESS.CITY, ADDRESS.STATE, ADDRESS.ZIP,  FROM ADDRESS INNER JOIN CONTACT ON ADDRESS.ADDRESS_ID = CONTACT.ADDRESS_ID INNER JOIN NAME ON CONTACT.NAME_ID = NAME.NAME_ID;
